model:
    name: 'generic_sfm'
    depth:
        name: 'DispNetS'
        file: 'disp_net'
        version: '1'
    pose:
        name: 'PoseNet'
        file: 'pose_net'
        version: '1'
datasets:
    path: '../KITTI/'
    augmentation:
        image_width: 1242
        image_height: 375
        shuffle: True
    sequence_length: 3
    dataset: ['KITTI']
    depth_type: ['velodyne']
action:
    mode : 'train'
    from_scratch : True
    split: [0.7, 0.15, 0.15]
    random_seed : 42
    batch_size: 4
    num_epochs: 10
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.1