model:
    name: 'test'
    depth:
        name: 'DispResNet'
        file: 'resnet_dispnet'
        version: '1'
    pose:
        name: 'PoseFc'
        file: 'pose_fc'
        version: '1'
datasets:
    path: '../KITTI/'
    split: './splits/kitti_ext.txt'
    augmentation:
        image_width: 1280
        image_height: 384
        shuffle: True
    sequence_length: 3
    dataset: ['KITTI']
action:
    mode : 'train'
    MLOps: False
    log_freq: 100
    from_scratch : True
    split: [0.8, 0.2]
    random_seed : 42
    batch_size: 4
    num_epochs: 30
    num_workers: 8
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0001
        pose:
            lr: 0.0001
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.1