model:
    name: 'sfm'
    depth:
        name: 'StnDispNet'
        file: 'stn_depth_net'
        version: '1'
    pose:
        name: 'PoseNet'
        file: 'pose_net'
        version: '1'
datasets:
    path: '../KITTI/'
    split: './splits/kitti_depth_annotated_train_files.txt'
    augmentation:
        image_width: 1242
        image_height: 375
        shuffle: True
    sequence_length: 3
    dataset: ['KITTI']
action:
    mode : 'train'
    MLOps: False
    log_freq: 100
    from_scratch : True
    split: [0.8, 0.2]
    random_seed : 42
    batch_size: 4
    num_epochs: 2
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.1