name: train_model
on: [push]
jobs:
  run:
    runs-on: [self-hosted, cml, gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
         CODEBLOCK="\`\`\`"
         echo $CODEBLOCK > report.md
         nvidia-smi >> report.md
         echo $CODEBLOCK >> report.md
         
         cml-send-comment report.md

         python train.py
